apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: site-wordpress-issuer
spec:
  acme:
    email: email@here
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: site-wordpress-issuer-key
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: project_here
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json