apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  serviceName: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      initContainers:
      - name: chown-wp
        image: busybox:latest
        command:
        - /bin/chown
        - -R
        - "1001"
        - /bitnami/wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /bitnami/wordpress
      containers:
        - name: wordpress
          image: bitnami/wordpress:latest
          env:
          - name: MARIADB_HOST
            value: wordpress-mysql
          - name: MARIADB_PORT
            value: "3306"
          - name: WORDPRESS_DATABASE_USER
            value: wordpress
          - name: WORDPRESS_DATABASE_NAME
            value: wordpress
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: site-wordpress-secrets
                key: wordpress_database_password
          - name: WORDPRESS_SCHEME
            value: https
          - name: WORDPRESS_BLOG_NAME
            value: wordpress-site
          - name: WORDPRESS_USERNAME
            value: admin
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: site-wordpress-secrets
                key: wordpress_password
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /bitnami/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim